### ISSUE TITLE
Deleting projects works only after manually switching to another project

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#1075]
### TODO
_(Added by @marc-vdm)_
- [ ] Once delete project is clicked, open default project, if it does not exist, open the first project in the projects list that is not the current project.
- [ ] Delete the previous project
- [ ] Write confirmation dialog informing user the project was successfully deleted.
Note: don't worry about deleting projects when there is only 1 project, AB already doesn't allow deleting the only project.

### Updating AB

- [X] Yes, I have [updated AB](https://github.com/LCA-ActivityBrowser/activity-browser#updating-the-ab) and still experience this issue

### What happened?

Not strictly a "bug", but probably not working fully as intended yet. 

When deleting a project, it seemingly does not do anything. In the console it gives a "PermissionError". It does not delete the project as the user is still "in" the project. So the AB should switch to another project (best do "default", or create default if not available) and then delete the project. It should also give the user feedback, e.g. a pop-up saying "Project X has been successfully deleted". 

### Relevant errors

```python
Loaded project:ei39
Traceback (most recent call last):
  File "C:\Users\steub\miniconda3\envs\ab\lib\site-packages\activity_browser\controllers\project.py", line 116, in delete_project
    bw.projects.delete_project(bw.projects.current, delete_dir=True)
  File "C:\Users\steub\miniconda3\envs\ab\lib\site-packages\bw2data\project.py", line 302, in delete_project
    shutil.rmtree(dir_path)
  File "C:\Users\steub\miniconda3\envs\ab\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\steub\miniconda3\envs\ab\lib\shutil.py", line 624, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\steub\miniconda3\envs\ab\lib\shutil.py", line 629, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\steub\miniconda3\envs\ab\lib\shutil.py", line 627, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\steub\\OneDrive - Universiteit Leiden\\Brightway3\\ei39.f1469ad5eb0a071dc60323f6e0fce980\\lci\\databases.db'
```

### Operating system

Windows 10
