### ISSUE TITLE
Improvements to Biosphere use

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#1142]
## Current situation:
Managing biosphere versions in AB projects is currently not ideal. Creating a new project installs the most recent version of the biosphere, potentially losing compatibility with older versions. (e.g. #1137).

### Biosphere import when project is started
- When starting a project, Biosphere data needs to be imported before doing anything else
- AB then installs the most recent version of the biosphere available

![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/34626062/9711d824-a4a0-4056-b313-10e65e38ddcd)
![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/34626062/b818dace-97fd-4628-8a9f-871297cd2eaa)

https://github.com/LCA-ActivityBrowser/activity-browser/blob/fe69950ac930a9cdaed5271ff39be2849cbdc516/activity_browser/ui/widgets/dialog.py#L529-L532

### Biosphere importer in Brightway
- When AB calls `bw.create_default_biosphere3()` eventually [`Ecospold2BiosphereImporter(name="biosphere3", version="3.9")`](https://github.com/brightway-lca/brightway2-io/blob/b19fae87ced639d0d8f5e700ab00125347c61040/bw2io/importers/ecospold2_biosphere.py#L16) is called

### Updating Biosphere
- When updating biosphere, AB looks for patches in `bw2io.data`
- And applies all patches

![image](https://github.com/LCA-ActivityBrowser/activity-browser/assets/34626062/569e5d94-91de-49a4-8c42-cb66144eba8a)
https://github.com/LCA-ActivityBrowser/activity-browser/blob/fe69950ac930a9cdaed5271ff39be2849cbdc516/activity_browser/ui/widgets/biosphere_update.py#L44
https://github.com/LCA-ActivityBrowser/activity-browser/blob/fe69950ac930a9cdaed5271ff39be2849cbdc516/activity_browser/ui/widgets/biosphere_update.py#L52-L55

## Proposal
What I propose is the following (explained more extensively in sections below):
- We let user specify the version of ecoinvent they want their biosphere to be compatible with when importing default data
- We let user specify which version of ecoinvent to update to when updating biosphere data
- We create an online (hosted on this github repo) file that contains all ecoinvent versions AB is compatible with (currently `3.4`-`3.9.1`), we then use this file for:
  - Showing which versions of ecoinvent can be imported (see also #1141)
  - Showing which ecoinvent-compatible version of biosphere to install on project creation
  - Showing which ecoinvent-compatible version of biosphere to update to

### Downloading a specific version of biosphere
Should provide popup that allows user to choose ecoinvent-compatible version, sorted from highest to lowest
Should provide information that biosphere databases are not always backwards compatible (e.g. ei 3.8 does not work on biosphere for ei 3.9) and that versions cannot be downgraded

#### TODO
- [x] Add dialog option to choose version (default to highest)
- [x] Replace `bw.create_default_biosphere3()` with an AB version that can call  [`Ecospold2BiosphereImporter(name="biosphere3", version="3.9")`](https://github.com/brightway-lca/brightway2-io/blob/b19fae87ced639d0d8f5e700ab00125347c61040/bw2io/importers/ecospold2_biosphere.py#L16) directly and call on chosen version
- [x] Read available version from variable somewhere (see __Host file online__ section below)

### Updating to specific version
Should provide popup that allows user to choose ecoinvent-compatible version, sorted from highest to lowest
Should provide information that biosphere databases are not always backwards compatible (e.g. ei 3.8 does not work on biosphere for ei 3.9) and that versions cannot be downgraded

#### TODO
- [x] Add dialog option to choose version (default to highest)
- [x] Only apply patches to max chosen version
- [x] Read available version from variable somewhere (see __Host file online__ section below)

### Show limited list of available ecoinvent versions for importing
Should limit the list of ecoinvent versions shown available for import

#### TODO
- [x] Read available version from variable somewhere (see __Host file online__ section below)

### Host file online
Host a file on our github with a list per AB version about what ecoinvent versions are compatible
- Why online? This way users don't need to update AB for the list to be updated, but it would mean we need to keep a list for every version of AB
  - In case a new version of `bw2io` comes available that is compatible with current version of AB, we don't need users to update AB, we just update the compatibility list online and it should work
  - In case a new `patch` version of ecoinvent becomes available (e.g. `3.9.1`, we can also just update the list, not requiring users to update AB
  - We can smartly write the implementation so we only need to store new version list when something changes
    - if user has AB `2.11` and the online list has `2.12` and `2.10` available, we choose the first version where AB is higher than list version (in this case `2.10`)
  - file could look something like this:
    - 2.10.2: [3.4, 3.5, 3.6, 3.7, 3.7.1, 3.8, 3.9, 3.9.1, 3.10]
    - 2.10: [3.4, 3.5, 3.6, 3.7, 3.7.1, 3.8, 3.9, 3.9.1]

#### TODO
- [x] Write file like suggested above
- [x] Read file from internet 
- [x] Local fallback in case of no connection
