### ISSUE TITLE
Add CPC and ISIC classification to metadatastore so that it can be use for aggregation

### ISSUE THREAD

**Issue by bsteubing** [LCA-ActivityBrowser/activity-browser#596]
Just like we can already aggregate LCIA results (e.g. in process contributions) by reference product, name or location, we should add [CPC](https://unstats.un.org/unsd/classifications/Econ/CPC.cshtml) and [ISIC](https://unstats.un.org/unsd/classifications/Econ/isic) classification data (not sure if the latter is imported by bw) to the metadatastore so that we can aggregate process contributions by these.

**Comment by marc-vdm** [comment]
Update to this: The data is imported to the metadatastore (see #632).

**Comment by marc-vdm** [comment]
Thoughts/Update to make this more useable:

### current state
We already load `classifications` to [`MetaDataStore`](https://github.com/LCA-ActivityBrowser/activity-browser/blob/b72f0057f85ccd388d89652abd6be3d82e988590/activity_browser/bwutils/metadata.py#L17). It's easiest to see the output by adding `classifications` to [this](https://github.com/LCA-ActivityBrowser/activity-browser/blob/b72f0057f85ccd388d89652abd6be3d82e988590/activity_browser/ui/tables/models/inventory.py#L59) list and opening an ecoinvent database in AB. See [here](https://user-images.githubusercontent.com/34626062/203643063-18d378bc-0992-4bb4-95c2-0a35645d7671.png) for example output in AB.

### classification systems
`classifications` is a list with tuples, the tuples are formatted to contain the classification system and it's class e.g. `[('ISIC rev.4 ecoinvent', '2420:Manufacture of basic precious and other non-ferrous metals'), ('CPC', '34612: Ammonium sulphate')]`. It seems two systems are available for most (all?) systems: [`ISIC rev.4`](https://unstats.un.org/unsd/classifications/Econ/isic) and [`CPC`](https://unstats.un.org/unsd/classifications/Econ/CPC.cshtml). 

**TODO**
 - [ ] Figure out if `ISIC rev.4` or `CPC` would be 'better' for LCA data. e.g. more focused on technical vs agricultural products (documentation for both systems in ISIC/CPC links above)
 - [ ] For both systems different versions exist. Figure out if different versions are often used in different ecoinvent versions? (pro for ISIC, it has rev.4 in name, so we know the version at least)
 - [ ] Decide which classification would be best to use in AB

### using a system in AB
There are a few obvious places to use classification in AB
1. In the `Activities` table in AB
   - The easy version would be to just show a classification
   - The _cool_ way would be to implement a tree view for the database based on the classification (see also #632)
     - AB would need to detect whether the shown database has classifications and enable a tree/list view option like we have with impact categories to view the tree. (we could just always show the radio buttons, and grey out the tree if it's not compatible with the database)
       - tangent on a tangent: We could also make a tree view for `biosphere` databases based on their compartments
2. In process contribution analysis of results
   - Here, user would be able to filter on a certain level of the classification
   - An even _cooler_ way would be to filter on all levels at once with a [sunburst](https://duckduckgo.com/?t=ffab&q=sunburst+graph&iax=images&ia=images) graph
     - We could even show a treeview of results impacts following the classifications
     - Of course this would be better off in it's own tab as it wouldn't be related to the 'normal' process contributions tab anymore
3. Less interesting, but could still be nice: Allowing users to add a classification to their own processes, we could just add the field to the `Products` table in activity details

#### considerations for all uses
For both uses of a classification, we'd need a method to properly show the classification in the `MetaDataStore`. The current list with multiple methods is nice, but we'd need to extract the right information efficiently. Additionally, we need to know more about the structure of the classifications. This would mean storing the structure somewhere in AB, either as a variable in python code or as a file on disk (or look it up dynamically from internet?, the links above do have a `.txt` with the full classification system).

**TODO**
 - [ ] Find efficient system to get to the right class of an activity. Extracting and storing as an extra column in `MetaDataStore` perhaps? Or would only reading the list-->tuple when needed be faster?
 - [ ] What is a good way to store the overarching classification system structure somewhere? 
   - A file? A python variable? 
   - Where do we store it? 
   - How do we manage multiple versions of the classification?
   - How do we manage multiple ecoinvent versions in one project using different classification versions?

After all TODO above have been figured out, I think we can start looking at actual implementations for either Activities table/Process contributions/other uses.

Any help with TODOs from anyone is highly appreciated!
