### ISSUE TITLE
Database tree view

### ISSUE THREAD

**Issue by marc-vdm** [LCA-ActivityBrowser/activity-browser#632]
As discussed a few times, a tree view for databases would be nice to have, this could be based on some classification system already present in databases like ecoinvent.

For whoever picks this up:
Through other work, I found that the classifications are stored in the Metadatastore:

```
from activity_browser.bwutils import AB_metadata

db = AB_metadata.get_database_metadata(database_name)
```
This `db` object is a Pandas Dataframe, with a column `classifications`. Each entry is a list in which the classifications are stored as tuples: `(name of classification, class)`

Hope that saves some work for whoever picks this up.

### TODO
- [x] Put classifications [CSV file](https://unstats.un.org/unsd/classifications/Econ/isic) in static folder
- [x] Generate tree from file
- [x] Link processes to tree whenever database is opened with ISIC classifications --> time how long this will take to create
- [x] Write UI treeview --> how to deal with search between the tree/list?
- [ ] re-add functionality of drag/drop
- [ ] context menus --> include expand/collapse options
- [ ] Optional Add to each tree level the amount of children leaf nodes?
- [ ] Move things to superclass for shared method/activity class where possible
- [ ] Link widget signals to update search settings for following signals (#785):
  - signals.new_activity.connect()
  - signals.duplicate_activity.connect()
  - signals.duplicate_activities.connect()
  - signals.duplicate_activity_to_db.connect()
  - signals.delete_activity.connect()
  - signals.delete_activities.connect()

**Comment by marc-vdm** [comment]
See related discussion here
https://github.com/LCA-ActivityBrowser/activity-browser/issues/596#issuecomment-1325671704

**Comment by Joeytje50** [comment]
https://unstats.un.org/unsd/classifications/Econ/Download/In%20Text/ISIC_Rev_4_english_structure.Txt
This tree view should be incorporated in the static files, and then read by AB to build a tree view of the different categories.
On the branch https://github.com/marc-vdm/activity-browser/tree/including_classifications there are already some of these classifications loaded for most of the ecoinvent activities. The activities should be grouped under their respective tree view when showing it.

The tree should be built up similar to Impact Categories, and the filtering should be made to work similar to it. When not in the tree view, the categories should not necessarily be shown, although that might be discussed still.

Furthermore, dragging and dropping activities should still be possible: dragging a parent tree level should drag and drop all child levels.

Finally, it might be useful to make the tree view code work more general, i.e. to reuse the same class when building the tree view of different things.

Databases that do not have these classifications loaded, should disable the tree view. Databases always load in list view by default.

**Comment by marc-vdm** [comment]
One more thing:
It may be good to check out whether it's smart to move the storage of the data up to the [`ActivityBiosphereWidget`](https://github.com/LCA-ActivityBrowser/activity-browser/blob/master/activity_browser/layouts/tabs/project_manager.py#L169) instead of having two dataframes, one for the tree and one for the list, but perhaps that's not a problem at all since we already use the `MetaDataStore`. Happy to think along on this you want.

**Comment by marc-vdm** [comment]
> On the branch https://github.com/marc-vdm/activity-browser/tree/including_classifications there are already some of these classifications loaded for most of the ecoinvent activities.

The classifications are now available in `master`, so no need to base the branch of my fork, just from `master` is fine 👍

**Comment by marc-vdm** [comment]
Resolved in #1047
